const assert = require('node:assert/strict');
const prefs = require('../webapp/static/js/modules/chart-preferences.js');
const backups = require('../webapp/static/js/modules/saved-work.js');
const storage = new Map([['swingpulse-grid-divisions', JSON.stringify({'1H':'Q','4H':'M',D:'Y'})]]);
const disk = {getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v))};
let user='zabs', now=100, edits=0;
const a=prefs.create({storage:disk,key:()=>`prefs__${user}`,now:()=>now++,onChange:()=>edits++});
assert.equal(a.division('1H').code,'Q');
assert.equal(a.snapshot().grids['1H'].modifiedAt,0,'Migration does not overwrite a newer remote preference');
a.mergeRemote({grids:{D:{division:'H',modifiedAt:0}}});
assert.equal(a.division('D').code,'H','Untimed legacy choices converge to the synced copy');
const b=prefs.create({storage:{getItem:()=>null,setItem:()=>{}},key:()=>'',now:()=>200});
a.set('1H','M');b.set('4H','H');
a.mergeRemote(b.snapshot());b.mergeRemote(a.snapshot());
assert.equal(a.division('1H').code,'M');assert.equal(b.division('1H').code,'M');
assert.equal(a.division('4H').code,'H');assert.equal(b.division('4H').code,'H');
a.mergeRemote({grids:{'1H':{division:'Y',modifiedAt:1}}});assert.equal(a.division('1H').code,'M');
assert.equal(a.set('1H','W'),false);assert.equal(a.pending(b.snapshot()),false);
user='hemi';a.reload();assert.equal(a.division('1H').code,'Q','Another user has an independent store');
user='zabs';a.reload();assert.equal(a.division('1H').code,'M');
const backup={format:'SwingPulseBackup',version:1,user:'zabs',savedAt:'2026-10-10T00:00:00Z',data:{channels:{GOLD:{'1H':[{kind:'channel',p1:100,p2:110}]}},notes:{GOLD:'Watch the breakout'},watchlists:{lists:[{id:'one',name:'Main',items:['GOLD']}],mod:1},views:{},grids:a.snapshot(),overlay:{}}};
assert.equal(backups.summary(backups.parse(JSON.stringify(backup))).drawings,1);
assert.throws(()=>backups.parse('not json'));
assert.throws(()=>backups.parse('{"format":"SwingPulseBackup","version":1,"data":{"__proto__":{}}}'));
assert.throws(()=>backups.validate({...backup,version:99}));
assert.throws(()=>backups.validate({...backup,data:{...backup.data,channels:{GOLD:{D:[{kind:'ladder',p1:'bad'}]}}}}));
assert.ok(!JSON.stringify(backups.validate({...backup,password:'hidden',data:{...backup.data,syncToken:'hidden'}})).includes('hidden'),'Credentials are never exported');
console.log('PASS: grid migration, user isolation, independent device merges, older changes, backup validation and credential exclusion');
