"""
_active_config.py — MA500 profile (single active config).
All modules import from here.
"""
from config import (
    MA_PERIODS, SMALL_MA_RANGE, MA_MIDPOINT,
    HISTORY_YEARS, CACHE_DIR, MIN_ROWS_REQUIRED,
    VOLUME_LOOKBACK,
    PIVOT_LOOKBACK, KEY_LEVEL_TOUCH_TOLERANCE, KEY_LEVEL_CLUSTER_RANGE,
    MA_TOUCH_TOLERANCE, TREND_DURATION_THRESHOLD,
    WATCH_APPROACH_PCT, MIDPOINT_BOUNCE_PCT,
    MAX_PENETRATION_4H, MAX_PENETRATION_DAILY,
    SIGNAL_LOOKBACK_4H, SIGNAL_LOOKBACK_DAILY,
    P3P4_DEDUP_WINDOW, P2_DEDUP_WINDOW, TTP_COOLDOWN_BARS,
    RIBBON_COMPRESSION_THRESHOLD, ROC_PERIOD,
    SLOPE_LOOKBACK, NEUTRAL_SLOPE_THRESHOLD,
    OUTPUT_DIR, OUTPUT_COLUMNS,
    _tf_signal_columns,
)

ACTIVE_PROFILE = 'ma500'
