"""
_active_config.py — MA500 profile (single active config).
All modules import from here.
"""
from config import (
    INSTRUMENTS_FILE,
    MA_PERIODS, SMALL_MA_RANGE, MA_MIDPOINT,
    HISTORY_YEARS, CACHE_DIR, MIN_ROWS_REQUIRED,
    VOLUME_LOOKBACK,
    PIVOT_LOOKBACK, KEY_LEVEL_TOUCH_TOLERANCE, KEY_LEVEL_CLUSTER_RANGE,
    KEY_LEVEL_WINDOW_BARS, KEY_LEVEL_MAJOR_COUNT,
    MA_TOUCH_TOLERANCE, TREND_DURATION_THRESHOLD,
    WATCH_APPROACH_PCT, MIDPOINT_BOUNCE_PCT,
    MAX_PENETRATION_4H, MAX_PENETRATION_DAILY,
    SIGNAL_LOOKBACK_1H, SIGNAL_LOOKBACK_4H, SIGNAL_LOOKBACK_DAILY,
    SIGNAL_LOOKBACK_WEEKLY, SIGNAL_LOOKBACK_3D, SIGNAL_LOOKBACK_5M,
    FIVE_MIN_SIGNAL_CODES, FIVE_MIN_SIGNAL_LIVE_HOURS,
    P3P4_DEDUP_WINDOW, P2_DEDUP_WINDOW, TTP_COOLDOWN_BARS,
    RIBBON_COMPRESSION_THRESHOLD, ROC_PERIOD,
    SLOPE_LOOKBACK, NEUTRAL_SLOPE_THRESHOLD,
    TREND_UP_FRAC, TREND_DOWN_FRAC,
    H4_SOURCE, H4_SESSION_NORMALIZE, H4_BARS_PER_SESSION_TARGET,
    H1_SESSION_NORMALIZE, H1_BARS_PER_SESSION_TARGET,
    WEEKLY_RESAMPLE_RULE, REFIRE_PCT_WEEKLY, NEW_TREND_PCT_WEEKLY,
    THREE_DAY_EPOCH, THREE_DAY_SIZE, REFIRE_PCT_3D, NEW_TREND_PCT_3D,
    FIVE_MIN_PERIOD, TEN_MIN_RULE, FIVE_MIN_MAX_AGE_HOURS,
    TEN_MIN_BARS_PER_DAY_TARGET, TEN_MIN_NORMALIZE_ABOVE,
    FIVE_MIN_BARS_PER_DAY_TARGET, FIVE_MIN_NORMALIZE_ABOVE,
    INTRADAY_PREFIXES, TIMEFRAMES, TF_PREFIXES, TF_CODE_BY_PREFIX,
    OUTPUT_DIR, OUTPUT_COLUMNS,
    CONTEXT_RULES, CONF_TIER_ORDER,
    _tf_signal_columns,
)

ACTIVE_PROFILE = 'ma500'
