#!/usr/bin/env python3
"""Assert that a publish actually MOVED the data, not just that the job exited 0.

WHY THIS EXISTS (2026-08-13)
From roughly 2026-07-28 to 2026-08-13 every scheduled run went green while the
ledger, the radar, the sector series and the flavours file all sat frozen at a
2026-08-04 timestamp. Nothing was broken loudly: signal_ledger and
sector_activity fetch their existing series back from R2 before merging, r2.dev
answered 403 to the default urllib user agent, and both modules correctly
refused to save rather than clobber a series they could not read. The job had
nothing to fail on. status.json said 'ok'. The app showed no banner. Five weeks
of track record quietly did not happen.

publish-watchdog.yml covers "the job died". This covers "the job lived and the
data did not move" — the failure that actually occurred.

THE CENTRAL INVARIANT
Every accumulating file restamps its own timestamp with _now() on each save. So
a file whose timestamp is OLDER than this run did not get written this run, and
the only way that happens is a skipped save. Age is therefore the whole test —
no previous-run state has to be persisted anywhere, which is what keeps this
check honest across a cache eviction or a fresh checkout.

Age, not calendar date, on purpose. A date comparison has to reason about the
UTC midnight boundary (the 01:35 cron lands either side of it depending on how
long GitHub queues it) and about weekends. An age threshold has neither problem.

TWO THRESHOLDS, BECAUSE THERE ARE TWO QUESTIONS
  --max-age-hours 2 (what publish.yml passes, straight after a publish) asks
      "did THIS run write every file?" It is chosen against the run spacing,
      not picked round: the threshold has to be SMALLER than the gap between
      two consecutive runs, or a file the previous run wrote still looks fresh
      enough to pass. It was 3h while the tightest gap was 5h (09:35 → 14:35);
      the evening run added 2026-08-27 lands 14:35 → 17:05, a 2.5h gap, so 3h
      would now wave through a file this run skipped. A healthy file is seconds
      old, minutes if written early in a slow run. Nothing lands in between.

      CAVEAT, and it is not fixable from here: GitHub queues scheduled runs by
      1.5–3h, so two runs can LAND far closer together than their crons are
      spaced. A long-queued 14:35 and a prompt 17:05 could finish 30 min apart,
      inside any threshold worth setting. This check is therefore sound against
      the nominal schedule and best-effort against a badly queued one.
  32h (the default, for running this by hand) asks "is the live app stale right
      now?" and deliberately matches the flat 32h the stale banner uses since
      app.js v231 — so a hand run agrees with what a phone is showing rather
      than reporting a scary red failure four hours after a healthy publish.

Fetches send a real User-Agent. Sending 'Python-urllib' here would reproduce the
exact 403 this script exists to catch and report every file as unreachable.

Exit 1 fails the workflow step, which lets publish.yml's existing `if: failure()`
notifier flip status.json to 'failed' and raise the banner on the app.

Usage:
  python3 tools/health_check.py                    # "is the live app stale?" (32h)
  python3 tools/health_check.py --max-age-hours 3  # "did this run write it?" (CI)
  python3 tools/health_check.py --warn-only        # report, always exit 0
"""
import argparse
import gzip
import json
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

R2_BASE = 'https://pub-e74b1a3a64724b07a76b853093e21240.r2.dev/ma500'

# r2.dev 403s the default 'Python-urllib/3.x'. Same header the pipeline loaders
# send — see the note in sector_activity.py.
USER_AGENT = 'SwingPulse-healthcheck/1.0'

# Default is the hand-run question ("is the live app stale?"), matching the
# app's own 32h stale banner. publish.yml overrides it with 3.
MAX_AGE_HOURS = 32.0

# Files that MUST carry a timestamp from this run, and the key it lives under.
# These are the accumulating ones — every one of them was frozen during the
# 07-28..08-13 outage, and every one is read by the app.
TIMESTAMPED = [
    ('summary.json',             'fetched_at'),
    ('status.json',              'at'),
    ('signal_ledger.json',       'updated_at'),
    ('ledger_summary.json',      'generated_at'),
    ('sector_activity.json',     'updated_at'),
    ('sector_radar.json',        'generated_at'),
    ('instrument_flavours.json', 'generated_at'),
]

# Files the app loads that must at least fetch and parse. They are rebuilt from
# scratch every run, so there is no freeze mode to catch — only a broken upload.
PARSEABLE = [
    'signals.json', 'trends.json', 'names.json',
    'explanations.json', 'tv-map.json', 'ai-instruments.json',
]

# Deliberately unchecked, so that "not in this list" always means "should move":
#   backtest.json    — regenerated by hand, not by the pipeline; the UI prints
#                      its own generated_at, so a stale one is visible, not silent.
#   flow_volumes.json— orphaned. The flow tab was removed (app.js redirects it to
#                      dashboard) and CI republishes a 1-day file over the local
#                      history every run. Checking it would fail forever on data
#                      nothing reads.
EXEMPT = ['backtest.json', 'flow_volumes.json']

# A drought this long across 736 instruments has never happened — the quietest
# real day in the ledger still fired 9. Long enough to sit through a weekend
# plus a public holiday on either side, so it warns rather than fails.
STALE_CONTENT_DAYS = 5

# This check runs seconds after the upload, so a stale read here is at least as
# likely to be r2.dev serving the previous object as it is a genuinely skipped
# save. Re-read before calling it a failure: a real freeze stays stale through
# all three attempts, while propagation lag clears in one. Costs nothing on a
# healthy run — the retry only happens on a file that already looks wrong, and
# a false red banner on good data is worse than 40 seconds.
STALE_RETRIES = 2
STALE_RETRY_WAIT_S = 20


# An instrument whose newest daily bar is this far behind the rest of the board
# has stopped trading, whatever its cache still says. Measured against the
# board's own newest bar, never against today: the daily series drops the
# unfinished session, so on any given run every healthy instrument sits one or
# two days back and a weekend run sits three.
#
# 10 days is sized for the longest real market closure, not picked round —
# Japan's Golden Week and Lunar New Year each shut an exchange for about a week,
# and either can land against a weekend. Every dropout this has had to catch was
# far past that: EA was 16 days behind when it was found, FERG.L was 40.
#
# WHY THIS IS NOT COVERED BY missing_count (2026-08-27)
# EA went private on 2026-08-10 and Yahoo wiped its history; FERG.L died on
# 2026-07-17. Neither was ever reported missing, because origin's Actions cache
# still held their old parquet and the incremental fetch appended nothing to it
# — both published every day as "OK 3283 rows", frozen. The coverage counter
# only sees an instrument vanish; it cannot see one stop moving. The only thing
# that ever noticed was a runner with a cold cache, which did the full download,
# got 6 rows and 1 row, and dropped them — 41 days after FERG.L stopped.
MAX_INSTRUMENT_STALE_DAYS = 10


def _fetch(fname):
    """GET a published file, bypassing every cache between here and the bucket."""
    url = f'{R2_BASE}/{fname}?_hc={int(datetime.now(timezone.utc).timestamp())}'
    req = urllib.request.Request(url, headers={
        'User-Agent': USER_AGENT,
        'Cache-Control': 'no-cache, max-age=0',
        'Pragma': 'no-cache',
    })
    with urllib.request.urlopen(req, timeout=30) as r:
        body = r.read()
        # signals/trends/backtest are published gzipped (2026-09-11), and urllib
        # does not undo Content-Encoding the way a browser does.
        if body[:2] == b'\x1f\x8b':
            body = gzip.decompress(body)
        return json.loads(body.decode('utf-8'))


def _parse_ts(raw):
    """Parse the two timestamp dialects the pipeline emits, or return None.

    publish.py writes ISO-8601 ('2026-08-13T15:36:06Z'); the ledger and sector
    modules write _now()'s display form ('2026-08-13 15:36 UTC'). Both are UTC.
    """
    if not isinstance(raw, str) or not raw.strip():
        return None
    s = raw.strip()
    m = re.match(r'^(\d{4}-\d{2}-\d{2})[T ](\d{2}):(\d{2})(?::(\d{2}))?', s)
    if not m:
        return None
    day, hh, mm, ss = m.group(1), m.group(2), m.group(3), m.group(4) or '00'
    try:
        return datetime.strptime(f'{day} {hh}:{mm}:{ss}',
                                 '%Y-%m-%d %H:%M:%S').replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def _age_hours(ts):
    return (datetime.now(timezone.utc) - ts).total_seconds() / 3600.0


def _days_since(day_str):
    d = _parse_ts(f'{day_str} 00:00')
    return None if d is None else (datetime.now(timezone.utc) - d).days


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--warn-only', action='store_true',
                    help='report problems but always exit 0')
    ap.add_argument('--max-age-hours', type=float, default=MAX_AGE_HOURS)
    ap.add_argument('--max-stale-days', type=float,
                    default=MAX_INSTRUMENT_STALE_DAYS,
                    help='how far an instrument may lag the newest daily '
                         'bar on the board before it counts as frozen')
    args = ap.parse_args()

    failures, warnings = [], []
    payloads = {}

    print(f'Health check — {R2_BASE}')
    print(f'  freshness threshold: {args.max_age_hours}h\n')

    # ── 1. Everything the app reads must fetch and parse ──────────────────
    for fname, _ in TIMESTAMPED:
        try:
            payloads[fname] = _fetch(fname)
        except (urllib.error.URLError, ValueError, OSError) as exc:
            failures.append(f'{fname}: unreachable or unparseable — {exc}')

    for fname in PARSEABLE:
        try:
            payloads[fname] = _fetch(fname)
            print(f'  {fname:26} fetched OK')
        except (urllib.error.URLError, ValueError, OSError) as exc:
            failures.append(f'{fname}: unreachable or unparseable — {exc}')

    # ── 2. Did this run actually write them? ──────────────────────────────
    # The wording follows the threshold: at 3h a stale file means THIS run
    # skipped a save; at 32h it means the app itself is showing old data.
    verdict = ('this run did not write it, so a save was skipped'
               if args.max_age_hours <= 6
               else 'the live app is serving stale data')
    print()
    for fname, key in TIMESTAMPED:
        doc = payloads.get(fname)
        if doc is None:
            continue
        for attempt in range(STALE_RETRIES + 1):
            if not isinstance(doc, dict):
                failures.append(f'{fname}: not a JSON object')
                break
            ts = _parse_ts(doc.get(key))
            if ts is None:
                failures.append(
                    f'{fname}: no readable {key!r} (got {doc.get(key)!r})')
                break
            age = _age_hours(ts)
            if age <= args.max_age_hours:
                print(f'  {fname:26} {key} {age * 60:5.1f} min old  OK'
                      + (f'  (after {attempt} re-read)' if attempt else ''))
                break
            if attempt < STALE_RETRIES:
                print(f'  {fname:26} {key} looks {age:.1f}h old — re-reading '
                      f'in {STALE_RETRY_WAIT_S}s in case R2 has not propagated')
                time.sleep(STALE_RETRY_WAIT_S)
                try:
                    doc = payloads[fname] = _fetch(fname)
                except (urllib.error.URLError, ValueError, OSError) as exc:
                    failures.append(f'{fname}: unreachable on re-read — {exc}')
                    break
            else:
                failures.append(
                    f'{fname}: {key} is {age:.1f}h old ({doc[key]}) after '
                    f'{STALE_RETRIES} re-reads — {verdict}')

    # ── 3. Integrity of what got written ──────────────────────────────────
    print()
    summary = payloads.get('summary.json')
    if isinstance(summary, dict):
        missing = summary.get('missing_count')
        total, expected = summary.get('total'), summary.get('expected')
        if missing:
            failures.append(
                f'summary.json: {missing} instrument(s) missing from the run '
                f'— {(summary.get("missing") or [])[:8]}')
        else:
            print(f'  instruments               {total}/{expected} present  OK')
        if total is not None and expected is not None and total != expected:
            failures.append(f'summary.json: total {total} != expected {expected}')

        signals = payloads.get('signals.json')
        rows = signals.get('data') if isinstance(signals, dict) else None
        if isinstance(rows, list) and total is not None and len(rows) != total:
            failures.append(
                f'signals.json: {len(rows)} rows but summary says {total} '
                f'instruments — the app would render a partial board')

        # Present is not the same as moving. missing_count above only catches an
        # instrument that vanished; this catches one that is still published
        # every day off a cache that stopped receiving bars. See
        # MAX_INSTRUMENT_STALE_DAYS for why the comparison is against the
        # board's own newest bar rather than today.
        if isinstance(rows, list) and rows:
            dated, undated = [], []
            for row in rows:
                who = str(row.get('instrument_name') or '?')
                try:
                    bar = datetime.strptime(str(row.get('date') or ''),
                                            '%Y-%m-%d').date()
                except ValueError:
                    undated.append(who)
                    continue
                dated.append((bar, who))

            if dated:
                newest = max(bar for bar, _ in dated)
                frozen = sorted((((newest - bar).days, who)
                                 for bar, who in dated
                                 if (newest - bar).days > args.max_stale_days),
                                reverse=True)
                if frozen:
                    worst = ', '.join(f'{who} {age}d' for age, who in frozen[:8])
                    failures.append(
                        f'signals.json: {len(frozen)} instrument(s) frozen more '
                        f'than {args.max_stale_days:g}d behind the newest bar '
                        f'on the board ({newest}) — {worst}')
                else:
                    print(f'  instrument freshness      all within '
                          f'{args.max_stale_days:g}d of {newest}  OK')

            if undated:
                failures.append(
                    f'signals.json: {len(undated)} row(s) carry no daily bar '
                    f'date at all — {undated[:8]}')

    ledger = payloads.get('signal_ledger.json')
    if isinstance(ledger, dict):
        recs = ledger.get('records') or []
        if not recs:
            failures.append('signal_ledger.json: zero records — the track '
                            'record would render empty')
        else:
            newest = max((r.get('fire_date', '') for r in recs), default='')
            gap = _days_since(newest)
            print(f'  ledger                    {len(recs)} records, '
                  f'newest fire {newest}  OK')
            if gap is not None and gap > STALE_CONTENT_DAYS:
                warnings.append(
                    f'signal_ledger.json: newest fire is {newest} ({gap}d ago). '
                    f'Timestamps are fresh so saves ARE landing — either a real '
                    f'drought or fires stopped being detected.')

    activity = payloads.get('sector_activity.json')
    if isinstance(activity, dict):
        rows = activity.get('rows') or []
        newest = max((r.get('date', '') for r in rows), default='')
        gap = _days_since(newest)
        print(f'  sector series             {len(rows)} rows, newest {newest}  OK')
        if gap is not None and gap > STALE_CONTENT_DAYS:
            warnings.append(f'sector_activity.json: newest row is {newest} '
                            f'({gap}d ago) — the radar is drifting')

    status = payloads.get('status.json')
    if isinstance(status, dict) and status.get('state') != 'ok':
        failures.append(f'status.json: state is {status.get("state")!r}, not "ok"')

    # ── 4. Verdict ────────────────────────────────────────────────────────
    print()
    for w in warnings:
        print(f'  WARN  {w}')
    for f in failures:
        print(f'  FAIL  {f}')

    if failures:
        print(f'\nHealth check FAILED — {len(failures)} problem(s). '
              f'The publish ran but the data it should have moved did not move.')
        return 0 if args.warn_only else 1

    scope = ('present and written by this run' if args.max_age_hours <= 6
             else f'present and fresher than {args.max_age_hours:g}h')
    print(f'Health check passed'
          f'{f" with {len(warnings)} warning(s)" if warnings else ""} — '
          f'every file the app reads is {scope}.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
